### ISSUE TITLE
No module named 'bokeh.plotting.figure'

### ISSUE THREAD

**Issue by mno-93** [pluxbiosignals/biosignalsnotebooks#10]
Dear community,

I was using the biosignalsnotebooks python library in the past but recently, I am facing an import issue.
I just installed the library via pip install. I am running a notebook in jupyter notebook in a conda environment.
I also tried manually installing bokeh in the conda environment which didn't help.
Running pip show bokeh brings:

Name: bokeh
Version: 2.4.3
Summary: Interactive plots and applications in the browser from Python
Home-page: https://github.com/bokeh/bokeh
Author: Bokeh Team
Author-email: info@bokeh.org
License: BSD-3-Clause
Location: /homes/mnorden/miniconda3/lib/python3.10/site-packages
Requires: Jinja2, numpy, packaging, pillow, PyYAML, tornado, typing-extensions
Required-by: biosignalsnotebooks

I am using Python 3.11.4 in the conda environment.
Do you have any idea?

**Comment by GRamosPlux** [comment]
Dear @mno-93 ,

Thank you very much for opening this valuable discussion and for being an important part of our esteemed community of users!

Before exploring the pertinent question that you attentively described, we would like to sincerely apologize for the late reply.

Regarding the reported issue, indeed, your perception is totally correct, the **biosignalsnotebooks** package still requires an older version of **bokeh (v2.4.3)**.

Taking into consideration the valuable details that you attentively shared with the team, we have the perception that the `pip show bokeh` command was executed on **Python 3.10** instead of the **Python 3.11.4** environment.

```
Name: bokeh
Version: 2.4.3
...
Location: /homes/mnorden/miniconda3/lib/python3.10/site-packages
...
```

Hoping that you don't consider the following suggestion inadequate, would it be possible to check if the **bokeh (v2.4.3)** version is also the one installed on the **Python 3.11.4** environment?

The team will carefully wait for your extremely important feedback, wishing, in the meantime, a continuation of a positive day!

**My best and sincere regards,**
@GRamosPlux

**Comment by mno-93** [comment]
Indeed, this was the case. I don't have an issue anymore.

**Comment by GRamosPlux** [comment]
Dear @mno-93 ,

These are excellent news, thank you very much for the extremely attentive feedback!

Please, never hesitate to open a new **Issue** if you face other problems.

Meanwhile, the team strongly wishes you a continuation of an excellent day and that exciting discoveries will arise in your **Biosignals** researches!

**My best and sincere regards,**
@GRamosPlux
