### ISSUE TITLE
Python installation failing

### ISSUE THREAD

**Issue by Lenakeiz** [pluxbiosignals/biosignalsnotebooks#9]
Dear @GRamosPlux 

I am trying to install the biosignalnotebooks with python 3.10.5 and I receive this very generic error message.

![image](https://user-images.githubusercontent.com/8957206/230633988-45715fdf-7558-4609-8d17-cd1d709566ae.png)

Do you happen to know what it could be causing it?

Thank you.

Cheers

**Comment by GRamosPlux** [comment]
Dear @Lenakeiz,

Thank you very much for opening this **Issue** and for being an important part of our esteemed community of users!

Concerning the issue that was attentively reported, it is probably being caused by the name of the package.
In order to test this hypothesis, the team would like to recommend the replacement of the `pip install biosignalnotebooks` instruction by `pip install biosignalsnotebooks`.

I will carefully wait for your extremely valuable feedback, wishing, in the meantime, a continuation of a pleasant day.

**My best and sincere regards,**
@GRamosPlux

**Comment by Lenakeiz** [comment]
A
